// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeStack.Data;

#nullable disable

namespace PokeStack.Migrations
{
    [DbContext(typeof(PokeStackContext))]
    [Migration("20220328232947_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PokeStack.Models.PokeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("atk")
                        .HasColumnType("int");

                    b.Property<int>("def")
                        .HasColumnType("int");

                    b.Property<int>("hp")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pokeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("spA")
                        .HasColumnType("int");

                    b.Property<int>("spD")
                        .HasColumnType("int");

                    b.Property<int>("spe")
                        .HasColumnType("int");

                    b.Property<string>("type1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PokeModel");
                });
#pragma warning restore 612, 618
        }
    }
}
